---
- name: Install ClamAV on Ubuntu 22.04
  hosts: all
  become: yes
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes
    
    - name: Install ClamAV
      apt:
        name: clamav
        state: present
    
    - name: Install ClamAV daemon (optional)
      apt:
        name: clamav-daemon
        state: present

    - name: Ensure ClamAV is running
      service:
        name: clamav-daemon
        state: started
        enabled: yes
